custom_postgres:
  outputs:
    dev:
      dbname: destination_db
      host: host.docker.internal
      pass: secret
      port: 5434
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
dbt_finances:
  outputs:
    dev:
      dbname: financials
      host: postgres
      password: password
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: finances
  target: dev
