services:
  client:
    build: 
      context: ./client/
      dockerfile: ./Dockerfile
    develop:
      watch:
        - path: ./client/
          action: sync
          target: ./app/
          ignore:
            - node_modules/
        - path: ./client/package.json
          action: rebuild
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - finances
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:15.6
    environment:
      POSTGRES_USER: finances
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financials
    ports:
      - 5433:5432
    networks:
      - finances

  dbt_finances:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.1
    networks:
      - finances
    command:
      [
          "run",
          "--profiles-dir",
          "/root",
          "--project-dir",
          "/dbt",
          "--full-refresh"
      ]
    volumes:
      - ./dbt_finances:/dbt
      - ./.dbt:/root
    depends_on:
      - postgres
    environment:
      DBT_PROFILE: dbt_finances
      DBT_TARGET: dev

networks:
  finances:
    driver: bridge

