services:
  client:
    build: 
      context: ./client/
      dockerfile: ./Dockerfile
    develop:
      watch:
        - path: ./client/
          action: sync
          target: ./app/
          ignore:
            - node_modules/
        - path: ./client/package.json
          action: rebuild
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - finances
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PGUSER=finances
      - PGPASSWORD=password
      - PGDATABASE=financials
      - PGHOST=postgres
      - PGPORT=5432

  postgres:
    image: postgres:15.6
    environment:
      POSTGRES_USER: finances
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financials
    ports:
      - "5433:5432"
    networks:
      - finances

networks:
  finances:
    driver: bridge

